export const endpoints = {
  auth: {
    login: '/auth/login',
    logout: '/auth/logout',
    me: '/auth/me',
  },
  periods: '/periods',
  periodsActive: '/periods/active',
  departments: '/departments',
  department: (slug: string) => `/departments/${slug}`,
  departmentStructure: (slug: string) => `/departments/${slug}/structure`,
  managementStructures: '/management-structures',
  workPrograms: '/work-programs',
  workProgramHighlights: '/work-programs/highlights',
  workProgram: (slug: string) => `/work-programs/${slug}`,
  news: '/news',
  newsArticle: (slug: string) => `/news/${slug}`,
  gallery: '/gallery',
  galleryEvent: (slug: string) => `/gallery/${slug}`,
  resources: '/resources',
  resourceDownload: (id: number) => `/resources/${id}/download`,
  about: '/about',
  stats: '/stats',
  aspirations: '/aspirations',
  aspirationStats: '/aspirations/stats',
  aspirationTrack: (code: string) => `/aspirations/track/${code}`,
  // Admin endpoints
  admin: {
    periods: '/admin/periods',
    departments: '/admin/departments',
    department: (id: number | string) => `/admin/departments/${id}`,
    members: '/admin/members',
    member: (id: number | string) => `/admin/members/${id}`,
    managementStructures: '/admin/management-structures',
    managementStructure: (id: number | string) => `/admin/management-structures/${id}`,
    workPrograms: '/admin/work-programs',
    workProgram: (id: number | string) => `/admin/work-programs/${id}`,
    news: '/admin/news',
    newsArticle: (id: number | string) => `/admin/news/${id}`,
    gallery: '/admin/gallery',
    galleryEvent: (id: number | string) => `/admin/gallery/${id}`,
    galleryItems: (eventId: number | string) => `/admin/gallery/${eventId}/items`,
    galleryItem: (id: number | string) => `/admin/gallery/items/${id}`,
    resources: '/admin/resources',
    resource: (id: number | string) => `/admin/resources/${id}`,
    about: '/admin/about',
    stats: '/admin/stats',
    aspirations: '/admin/aspirations',
    aspirationsRespond: (id: number | string) => `/admin/aspirations/${id}/respond`,
  },
} as const;
