export const queryKeys = {
  periods: ['periods'] as const,
  periodActive: ['periods', 'active'] as const,
  departments: (periodId?: number) => ['departments', periodId ?? 'active'] as const,
  departmentStructure: (slug: string) => ['departments', slug, 'structure'] as const,
  managementStructures: (filters?: object) => ['management-structures', filters] as const,
  workPrograms: (filters?: object) => ['work-programs', filters] as const,
  workProgramHighlights: ['work-programs', 'highlights'] as const,
  workProgram: (slug: string) => ['work-programs', slug] as const,
  news: (filters?: object) => ['news', filters] as const,
  newsArticle: (slug: string) => ['news', slug] as const,
  gallery: (filters?: object) => ['gallery', filters] as const,
  galleryEvent: (slug: string) => ['gallery', slug] as const,
  resources: (filters?: object) => ['resources', filters] as const,
  about: ['about'] as const,
  stats: ['stats'] as const,
  aspirations: (filters?: object) => ['aspirations', filters] as const,
  aspirationStats: ['aspirations', 'stats'] as const,
  aspirationTrack: (code: string) => ['aspirations', 'track', code] as const,
};
