import { useEffect,useRef,useState } from 'react';
import {useQuery,useMutation,useQueryClient} from '@tanstack/react-query';
import {Plus,Search,Image,Edit2,Trash2,X,Upload,Loader2} from 'lucide-react';
import {motion} from 'motion/react';
import {apiClient} from '../../config/axios';
import {useActivePeriod} from '../../hooks/usePeriod';
import type {ApiResponse,GalleryEvent,PaginatedData} from '../../services/api.types';
interface Form{title:string;description:string;event_date:string;cover_image_url:string;is_published:boolean}
const EMPTY:Form={title:'',description:'',event_date:'',cover_image_url:'',is_published:true};
export default function AdminGalleryPage(){const qc=useQueryClient();const {data:period}=useActivePeriod();const [search,setSearch]=useState('');const [modal,setModal]=useState(false);const [edit,setEdit]=useState<number|null>(null);const [form,setForm]=useState(EMPTY);const [error,setError]=useState('');const [album,setAlbum]=useState<GalleryEvent|null>(null);const [files,setFiles]=useState<File[]>([]);const [drag,setDrag]=useState(false);const input=useRef<HTMLInputElement>(null);
const {data,isLoading}=useQuery({queryKey:['admin-galleries',period?.id],queryFn:()=>apiClient.get<ApiResponse<PaginatedData<GalleryEvent>>>('/admin/gallery',{params:{period_id:period?.id,per_page:50}}).then(r=>r.data.data),enabled:!!period?.id});
const save=useMutation({mutationFn:()=>{const body={...form,period_id:period?.id};return edit?apiClient.put(`/admin/gallery/${edit}`,body):apiClient.post('/admin/gallery',body)},onSuccess:()=>{qc.invalidateQueries({queryKey:['admin-galleries']});close()},onError:(e:any)=>setError(Object.values(e?.response?.data?.errors||{}).flat()?.[0]||e?.response?.data?.message||'Gagal menyimpan album')});
const remove=useMutation({mutationFn:(id:number)=>apiClient.delete(`/admin/gallery/${id}`),onSuccess:()=>qc.invalidateQueries({queryKey:['admin-galleries']})});
async function upload(){if(!album||files.length===0)return;setError('');try{for(const f of files){const fd=new FormData();fd.append('file',f);fd.append('type','photo');await apiClient.post(`/admin/gallery/${album.id}/items`,fd)}setFiles([]);setAlbum({...album});qc.invalidateQueries({queryKey:['admin-galleries']});alert(`${files.length} foto berhasil diupload.`)}catch(e:any){setError(Object.values(e?.response?.data?.errors||{}).flat()?.[0]||e?.response?.data?.message||'Upload foto gagal')}}
function addFiles(list:FileList|File[]){const next=Array.from(list).filter(f=>f.type.startsWith('image/'));setFiles(prev=>[...prev,...next])}
function close(){setModal(false);setEdit(null);setForm(EMPTY);setError('')}
useEffect(()=>{document.title='Galeri · HMDSI Admin'},[]);const galleries=data?.items?.filter(g=>g.title.toLowerCase().includes(search.toLowerCase()))||[];
return <div className="space-y-6"><div className="flex flex-col sm:flex-row sm:justify-between gap-4"><div><h2 className="text-white font-bold text-xl">Galeri</h2><p className="text-white/40 text-sm">Dokumentasi kegiatan periode {period?.name||'aktif'}.</p></div><button onClick={()=>{setForm(EMPTY);setEdit(null);setError('');setModal(true)}} className="flex items-center gap-2 px-4 py-2.5 bg-gradient-to-r from-[#0200B5] to-[#0000F0] text-white rounded-lg text-sm"><Plus className="w-4 h-4"/>Tambah Album</button></div><div className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-white/40"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Cari album..." className="w-full pl-10 pr-4 py-2.5 bg-white/5 border border-white/10 rounded-lg text-white text-sm"/></div><div className="grid sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4">{isLoading?[1,2,3,4].map(i=><div key={i} className="aspect-square bg-white/5 rounded-2xl animate-pulse"/>):galleries.map(g=><div key={g.id} className="bg-white/5 border border-white/10 rounded-2xl overflow-hidden"><div className="aspect-square bg-white/5">{g.cover_image_url?<img src={g.cover_image_url} className="w-full h-full object-cover"/>:<div className="w-full h-full flex items-center justify-center"><Image className="w-10 h-10 text-white/20"/></div>}</div><div className="p-4"><h3 className="text-white font-semibold text-sm truncate">{g.title}</h3><p className="text-white/40 text-xs mt-1">{g.items_count||0} foto</p><div className="grid grid-cols-3 gap-2 mt-3"><button onClick={()=>{setAlbum(g);setFiles([]);setError('')}} className="px-2 py-2 bg-[#0200B5]/20 text-[#9ba0ff] rounded-lg text-xs">Foto</button><button onClick={()=>{setEdit(g.id);setForm({title:g.title,description:g.description||'',event_date:g.event_date||'',cover_image_url:g.cover_image_url||'',is_published:g.is_published});setError('');setModal(true)}} className="px-2 py-2 bg-white/10 text-white rounded-lg text-xs">Edit</button><button onClick={()=>{if(confirm('Hapus album ini?'))remove.mutate(g.id)}} className="px-2 py-2 bg-red-500/10 text-red-400 rounded-lg text-xs"><Trash2 className="w-4 h-4 mx-auto"/></button></div></div></div>)}</div>
{album&&<div className="fixed inset-0 z-50 flex items-center justify-center p-4"><div className="absolute inset-0 bg-black/70" onClick={()=>setAlbum(null)}/><motion.div initial={{opacity:0,y:15}} animate={{opacity:1,y:0}} className="relative w-full max-w-2xl bg-[#0a0a1a] border border-white/10 rounded-2xl p-6"><div className="flex items-center justify-between mb-5"><div><h3 className="text-white font-bold">Dokumentasi: {album.title}</h3><p className="text-white/40 text-xs">Drag & drop foto ke area berikut.</p></div><button onClick={()=>setAlbum(null)} className="text-white/40"><X/></button></div>{error&&<div className="mb-4 p-3 bg-red-500/10 border border-red-500/30 rounded-lg text-red-300 text-sm">{error}</div>}<div onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);addFiles(e.dataTransfer.files)}} onClick={()=>input.current?.click()} className={`rounded-2xl border-2 border-dashed p-10 text-center cursor-pointer ${drag?'border-[#0200B5] bg-[#0200B5]/10':'border-white/15 bg-white/5'}`}><Upload className="w-8 h-8 text-white/40 mx-auto mb-3"/><p className="text-white text-sm">Tarik dan lepas foto di sini</p><p className="text-white/30 text-xs mt-1">JPG, PNG, WEBP, GIF · maksimum 10 MB/foto</p><input ref={input} type="file" accept="image/*" multiple hidden onChange={e=>e.target.files&&addFiles(e.target.files)}/></div>{files.length>0&&<div className="grid grid-cols-4 gap-2 mt-4 max-h-48 overflow-y-auto">{files.map((f,i)=><div key={i} className="relative"><img src={URL.createObjectURL(f)} className="aspect-square rounded-lg object-cover"/><button onClick={()=>setFiles(prev=>prev.filter((_,j)=>j!==i))} className="absolute top-1 right-1 p-1 bg-black/70 rounded-full text-white"><X className="w-3 h-3"/></button></div>)}</div>}<div className="flex gap-3 mt-5"><button onClick={()=>setAlbum(null)} className="flex-1 px-4 py-2.5 bg-white/5 text-white/70 rounded-lg">Tutup</button><button onClick={upload} disabled={!files.length} className="flex-1 px-4 py-2.5 bg-[#0200B5] text-white rounded-lg flex items-center justify-center gap-2">{files.length?`Upload ${files.length} Foto`:'Pilih Foto'}</button></div></motion.div></div>}
{modal&&<div className="fixed inset-0 z-50 flex items-center justify-center p-4"><div className="absolute inset-0 bg-black/70" onClick={close}/><motion.div initial={{opacity:0,y:15}} animate={{opacity:1,y:0}} className="relative w-full max-w-lg bg-[#0a0a1a] border border-white/10 rounded-2xl p-6"><div className="flex justify-between mb-5"><h3 className="text-white font-bold">{edit?'Edit Album':'Album Baru'}</h3><button onClick={close} className="text-white/40"><X/></button></div>{error&&<div className="mb-4 p-3 bg-red-500/10 border border-red-500/30 rounded-lg text-red-300 text-sm">{error}</div>}<div className="space-y-4"><input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Judul album" className="w-full px-3 py-2.5 bg-white/5 border border-white/10 rounded-lg text-white"/><input type="date" value={form.event_date||''} onChange={e=>setForm({...form,event_date:e.target.value})} className="w-full px-3 py-2.5 bg-white/5 border border-white/10 rounded-lg text-white"/><input value={form.cover_image_url} onChange={e=>setForm({...form,cover_image_url:e.target.value})} placeholder="URL cover (opsional)" className="w-full px-3 py-2.5 bg-white/5 border border-white/10 rounded-lg text-white"/><textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Deskripsi" rows={3} className="w-full px-3 py-2.5 bg-white/5 border border-white/10 rounded-lg text-white"/><label className="flex gap-2 items-center text-white/60 text-sm"><input type="checkbox" checked={form.is_published} onChange={e=>setForm({...form,is_published:e.target.checked})}/> Publikasikan album</label><div className="flex gap-3"><button onClick={close} className="flex-1 px-4 py-2.5 bg-white/5 text-white/70 rounded-lg">Batal</button><button onClick={()=>{if(!form.title.trim()){setError('Judul album wajib diisi');return}save.mutate()}} disabled={save.isPending} className="flex-1 px-4 py-2.5 bg-[#0200B5] text-white rounded-lg flex justify-center gap-2">{save.isPending&&<Loader2 className="w-4 h-4 animate-spin"/>}Simpan</button></div></div></motion.div></div>}</div>
}
