<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('aspirations', function (Blueprint $table) {
            $table->id();
            // Format: ASP-YYYY-XXXXX — generated by backend, used for public status tracking
            $table->string('tracking_code', 20)->unique()->index();
            $table->enum('category', [
                'academic',
                'facility',
                'internal',
                'general',
                'other',
            ])->index();
            $table->string('subject', 200);
            $table->text('message');
            $table->enum('status', [
                'submitted',
                'under_review',
                'in_progress',
                'resolved',
                'rejected',
            ])->default('submitted')->index();
            $table->boolean('is_anonymous')->default(false);
            // Only filled when is_anonymous = false
            $table->string('sender_name', 100)->nullable();
            $table->string('sender_email', 150)->nullable();
            $table->string('sender_student_id', 20)->nullable(); // NIM for verification
            // If true, appears in public tracker with anonymized data
            $table->boolean('is_public')->default(false)->index();
            $table->timestamp('resolved_at')->nullable();
            $table->timestamps();
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('aspirations');
    }
};
